### ISSUE TITLE
suspicious spam emails

### ISSUE THREAD

**Issue by Trojaner** [Zhen-Dong/Magic-Me#9]
While this seems like legitimate project with good intentions, you violate various laws and the GitHub Terms of Usage by scraping GitHub emails and sending spam advertisement emails for this project.

Please stop sending spam emails and never do this again.

![olk_MUxHgD61SU](https://github.com/Zhen-Dong/Magic-Me/assets/1809172/434c4bf4-9fd3-4e4a-a94c-5ebf054bf3ad)

**Comment by visionMaze** [comment]
Thank you for bringing this to our attention. We are not aware of this. Please block the email address sending this and forward the email to me so that we can do further investigations. Thank you!
